---
title: "Homework 1"
author: "Cameron Kay, Lea Frank, and Ashley L. Miller"
date: "1/23/2019"
output:
  html_document:
    highlight: zenburn
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r setup, include = FALSE}

# set knitr options
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.width = 7.5,
                      fig.height = 4.0)

# load packages
library(rio)
library(here)
library(tidyverse)
library(magrittr)
library(ggforce)

# disable scientific notation
options(scipen = 999)

```

```{r load_data}

# load data (7 files total)

data_assess <- import(here::here("data", "assessments.csv"),
                      setclass = "tibble") %>%
  janitor::clean_names()

data_courses <- import(here::here("data", "courses.csv"),
                       setclass = "tibble") %>% 
  janitor::clean_names()

data_std_assess <- import(here::here("data", "studentAssessment.csv"),
                          setclass = "tibble") %>% 
  janitor::clean_names()

data_std_info <- import(here::here("data", "studentInfo.csv"),
               setclass = "tibble") %>% 
  janitor::clean_names()

data_std_regist <- import(here::here("data", "studentRegistration.csv"),
               setclass = "tibble") %>% 
  janitor::clean_names()

data_std_vle <- import(here::here("data", "studentVle.csv"),
               setclass = "tibble") %>% 
  janitor::clean_names()

data_vle <- import(here::here("data", "vle.csv"),
               setclass = "tibble") %>% 
  characterize() %>%
  janitor::clean_names()

```

```{r identify_keys, include=FALSE}

# identify key in course data:
# key = code_module + code_presentation

data_courses %>% 
  count(code_module, code_presentation) %>% 
  filter(n > 1)

# identify key in assessment data:
# key = id_assessment

data_assess %>% 
  count(id_assessment) %>% 
  filter(n > 1)

# identify key in VLE data:
# key = id_site

data_vle %>% 
  count(id_site) %>% 
  filter(n > 1)

# identify key in student info data:
# key = code_module + code_presentation + id_student

data_std_info %>% 
  count(code_module, code_presentation, id_student) %>% 
  filter(n > 1)

# identify key in student registration file
# key = code_module + code_presentation + id_student

data_std_regist %>% 
  count(code_module, code_presentation, id_student) %>% 
  filter(n > 1)

# identify key in student assessment data:
# key = id_student + id_assessment

data_std_assess %>% 
  count(id_student, id_assessment) %>% 
  filter(n > 1)

####################################
# Identify key in student VLE file:
# NO KEY
####################################

data_std_vle %>% 
  count(code_module, code_presentation, id_student, id_site, date, sum_click) %>% 
  filter(n > 1)

# create surrogate key?
data_std_vle %<>% 
  rowid_to_column()

data_std_vle %>%
  count(rowid) %>%
  filter(n > 1)

```

#### 1) Mutating join/data visualization #1 (Ashley's)

  + **Mutating join**

```{r ash_mutating_join}

ash_data <- left_join(data_std_assess, data_std_info, by = "id_student") #joined by id_student

# identify key
# ash_data %>% 
  # count(id_assessment, id_student, code_module, code_presentation) %>% key
  # filter(n > 1)

ash_data <- ash_data %>%
  group_by(id_student) %>%
  summarize(mean_score = mean(score)) %>%
  left_join(ash_data)

ash_data %<>%
  select(id_student, mean_score, gender:age_band) %>%
  distinct(id_student, .keep_all = TRUE)

```

  + **Resulting data visualization(s)**

```{r ash_data_visualization}

ggplot(ash_data, aes(x = age_band, y = mean_score, fill = age_band)) +
  geom_violin() +
  ggforce::geom_sina(size = 0.5) +
  geom_boxplot(alpha = 0) +
  scale_fill_manual(values = c("#157381", "#4D306E", "#C0A5E1")) +
  facet_wrap(~gender) +
  theme_bw() +
  labs(title = "Figure 1.",
       subtitle = "Assessment score distributions by age group and gender",
       x = "Age Group", 
       y = "Mean Assessment Score",
       caption = "Data from https://analyse.kmi.open.ac.uk/open_dataset") +
  theme(legend.position = "none")

ggplot(ash_data, aes(x = highest_education, y = mean_score, fill = highest_education)) +
  geom_violin() +
  ggforce::geom_sina(size = 0.5) +
  geom_boxplot(alpha = 0) +
  scale_fill_viridis_d() +
  theme_bw() +
  labs(title = "Figure 2.",
       subtitle = "Assessment score distributions by level of education",
       x = "Education Level", 
       y = "Mean Assessment Score",
       caption = "Data from https://analyse.kmi.open.ac.uk/open_dataset") +
  theme(legend.position = "none")

```

#### 2) Mutating join/data visualization #2 (Cam's)

  + **Mutating join**

```{r cam_mutating_join}
# join student information with student vle use
cam_data <- left_join(data_std_info, data_std_vle, by = "id_student")

# drop redundant columns
cam_data %<>%
  select(-contains(".y"))

#summarize students average number of clicks per module
cam_data %<>%
  group_by(id_student) %>% # group by student
  summarize(sum_click_m = mean(sum_click, na.rm = TRUE)) %>% # calculate average number of clicks on VLE materials
  filter(!is.na(sum_click_m)) %>% # remove students who only visited once or who have no imd_band
  left_join(data_std_info) %>% # join demographics with summarized data
  select(id_student, # select only the columns of interest 
         sum_click_m,
         gender,
         region,
         highest_education,
         imd_band,
         age_band) %>%
  filter(imd_band != "", # drop cases with no value for imd band
         age_band != "55<=") %>% # drop cases with insufficient data for age band
  mutate(region = if_else(region != "Scotland" & # mutate regions to sort by countries
                          region != "Ireland" &
                          region != "Wales", 
                          "England", 
                          region),
         imd_band_num = parse_number(imd_band)) # change imd_band from a factor to a numeric
```

  + **Resulting data visualization(s)**
  
```{r cam_data_visualization}
# plot
ggplot(cam_data, aes(x = imd_band_num, y = sum_click_m)) +
  geom_jitter(size = .7, alpha = .7, aes(color = sum_click_m), width = 10, height = 1) +
  geom_smooth(method = "lm", se = FALSE, color = "deeppink2", lwd = 1.5, alpha = .8) +
  theme_bw() +
  theme(strip.background = element_rect(fill = "gray22"),
        strip.text = element_text(colour = "white"),
        legend.position = "none") +
  ylim(0, 10) +
  scale_color_gradient2(low = "cyan", mid = "dodgerblue3", high = "dodgerblue3", midpoint = 8) +
  facet_grid(~region) +
  labs(title = "Figure 3.",
       subtitle = "Relationship between deprivation and amount of engagement with VLE materials",
       x = "Index of Multiple Deprivation", 
       y = "Mean interactions with VLE",
     caption = "Data from https://analyse.kmi.open.ac.uk/open_dataset")
  
```

#### 3) Mutating join/data visualization #3 (Lea's)

```{r mutatejoin3}



```

#### 4) Filter join (Cam)

```{r filtering join}



```
  
#### 5) Reproduce the following figure:

```{r reproduce_figure}

data <- left_join(data_std_assess, data_std_info, by = "id_student") 

data$score = as.numeric(data$score)

data %<>%
  select(-date_submitted:-is_banked, -imd_band:-disability) %>%
  group_by(highest_education, gender, final_result) %>%
  summarize(mean_score = mean(score, na.rm = TRUE))

ggplot(data, aes(x = highest_education, y = mean_score)) +
  geom_col(aes(fill = gender),
           position = "dodge",
           alpha = 0.6) +
  scale_fill_manual(values = c("#10A0AC", "#430E70")) +
  facet_wrap(~final_result, nrow = 4) +
  coord_flip() +
  theme_minimal() +
  labs(title = "Average TMA Scores",
       subtitle = "Results Displayed by Education, Gender, and Final Result Designation",
       x = "Highest Education", 
       y = "Average Score",
       caption = "Data from Kuzilek, Hlosta, & Zdrahal (2017).
       Data from https://analyse.kmi.open.ac.uk/open_dataset",
       fill = "Gender")
  
```